service: YOUR_NAMESPACE-service

frameworkVersion: ">=1.4.0 <2.0.0"

package:
  exclude:
    - npm-scripts/**
    - s3-cors.json
    - config/dev.skill.config.json
    - config/prod.skill.config.json    
    # remove node modules only needed for npm scripts
    - node_modules/attrs.argv/**
    - node_modules/cp/**
    - node_modules/npm-run-script/**
    - node_modules/prompt/**
    - node_modules/mocha/**
    - node_modules/urldecode/**
    - node_modules/opn/**

provider:
  name: aws
  runtime: nodejs4.3
  region: YOUR_REGION
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  memorySize: 128

custom:
  defaultStage: dev
  profiles:
    dev: YOUR_NAMESPACE-profile-dev
    prod: YOUR_NAMESPACE-profile-prod

functions:
  skill:
    handler: main.handler
    events:
      - alexaSkill 
